[package]
name = "titan"
version = "0.1.0"
authors = ["Eric Dattore <edattore@gmail.com>"]

[lib]
path = "src/lib.rs"
name = "libtitan"

[[bin]]
path = "src/bin/main.rs"
name = "titan"

[dependencies]
rocket = { git = "https://github.com/ELD/Rocket", branch = "connection-pool" }
rocket_contrib = { git = "https://github.com/ELD/Rocket", branch = "connection-pool", features = ["databases", "diesel_mysql_pool"] }
rocket_codegen = { git = "https://github.com/ELD/Rocket", branch = "connection-pool" }
diesel = { version = "1.0", features = ["mysql", "r2d2", "serde_json"] }
serde = "1.0"
serde_derive = "1.0"